version: 3

vars:

  NAME: ghcr.io/nuvolaris/trustable-devcontainer
  OPSROOT: ../olaris-tr/opsroot.json

  TAG:
    sh: git tag --sort=-creatordate | head -n 1 || "latest"

tasks:
  default: task --list-all

  show: "echo {{.NAME}}:{{.TAG}}"

  update-json:
    silent: true
    cmds:
    - jq . {{.OPSROOT}} >_opsroot.orig
    - jq '.config.images.trustable = "{{.NAME}}:{{.TAG}}"' {{.OPSROOT}} >_opsroot.json
    - diff _opsroot.orig _opsroot.json || cp -v _opsroot.json {{.OPSROOT}}

  image-tag:
      - git tag -d "$(git tag)" || true
      - git tag "0.1.0-incubating.$(date +%y%m%d%H%M)"
      - echo {{.NAME}}:$(git tag --sort=-creatordate | head -n 1)

  build:
      - test -d workspace || die "please git clone git@github.com:nuvolaris/trustable-workspace workspace"
      - docker build -t "{{.NAME}}:{{.TAG}}" . --load
      - task: show

  clean:
      - docker rm -f ssh-devcontainer || true
      - docker images | awk '/<none>|devcontainer/{print $3}' | xargs docker rmi -f || true

  build-and-tag:
    - task: image-tag
    - task: build
